### ISSUE TITLE
Annotation processors must be explicitly declared now

### ISSUE THREAD

**Issue by Angads25** [googlesamples/android-custom-lint-rules#16]
Getting ->
Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.
  - intellij-core-26.2.0.jar (com.android.tools.external.com-intellij:intellij-core:26.2.0)
Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.

when using dependencies:

      implementation "com.android.tools.lint:lint-api:26.2.0"
      implementation "com.android.tools.lint:lint-checks:26.2.0"

**Comment by onevilas** [comment]
I am facing same issue on 26.2.1. Any updates on this?
