### ISSUE TITLE
Documentation on the lint dependencies

### ISSUE THREAD

**Issue by btrautmann** [googlesamples/android-custom-lint-rules#18]
As discussed [here](https://groups.google.com/forum/#!topic/lint-dev/_MDyEHLTNCg) I intend to open a PR adding summaries of the lint dependencies here for others that want to know what each one is used for.

**Comment by gharrma** [comment]
Looks good to me!
@nageshs, mind taking a look? It might also make sense to give Tor and/or me write access to this repo, if desired.
