### ISSUE TITLE
[Question] How to apply lint rules from custom project in jcenter

### ISSUE THREAD

**Issue by GuilhE** [googlesamples/android-custom-lint-rules#26]
I've created and published a lib containing some custom lint rules.
Now I want to import it in my projects through a gradle dependency.

If I follow the **android-studio-4** approach (empty library module with `lintPublish(":checks:")` will it work if latter in my project I do something like: `lintChecks("my.project.lint:1.2.3")`?

Thanks.

**Comment by LeonDevLifeLog** [comment]
As far as i known,custom lint is a java library,after you published you can do as you say.That can check your code if you add this dependency to app module or library module.
