### ISSUE TITLE
I can't find any doc about lombok.ast

### ISSUE THREAD

**Issue by GavinCT** [googlesamples/android-custom-lint-rules#3]
Can you help me?  any doc? 
What's [Select](http://grepcode.com/file/repo1.maven.org/maven2/com.android.tools.external.lombok/lombok-ast/0.2.1/lombok/ast/Select.java) mean?

**Comment by nageshs** [comment]
Can you elaborate the question a bit? Are you using this in a lint detetor? 
Also please look at other lint checks that use the ast e.g https://android.googlesource.com/platform/sdk/+/c266409/lint/libs/lint_checks/src/com/android/tools/lint/checks/UnusedResourceDetector.java
