### ISSUE TITLE
Changelog/Diff of lint library versions

### ISSUE THREAD

**Issue by a11n** [googlesamples/android-custom-lint-rules#4]
Hi,

a few hours ago you released new (beta) versions of the lint,lint-checks, lint-api and lint-test libraries [1]. Every time this happens I'm always very curious what exactly changed in regards to the previous version.

I've searched many of the tools where the code is hosted, e.g. [2][3], but was not abled to find an overview.

So, in one of the many tools you are using, is there such an overview or changelog available?

(Sorry for asking this here, this is not *directly* related to the this project, but I feel you might easily help me and all other Lint API users :-))

Thanks in advance,
André

1. https://bintray.com/android/android-tools/com.android.tools.lint.lint-api/24.5.0-beta3/view
2. https://android.googlesource.com/platform/tools/base/+/master/lint/libs/
3. https://android-review.googlesource.com/#/q/project:platform/tools/base

**Comment by nageshs** [comment]
André, 

Thank you for the question. I can totally understand the need for this information. Can you please post it in the adt-dev mailing list [1]

-- Nagesh
1. https://groups.google.com/forum/#!forum/adt-dev

**Comment by a11n** [comment]
Hi Nagesh,

thanks for your reply. I've posted the question to the ML:
https://groups.google.com/forum/#!topic/adt-dev/1Lsw7SDsb_8

I'll close the GH ticket. Answer is hopefully posted there :-)

Best regards,
André
