### ISSUE TITLE
How can I get the Detectors API details description?

### ISSUE THREAD

**Issue by tangken333** [googlesamples/android-custom-lint-rules#58]
I want to write my own rules, so I have read the Android Lint API Guide. But I found that the chapter about detectors just tell me what detectors lint have, do not tell me what method can I use and how to use. For example, i want to write a rule to check if there is a var name a in method b, how can i do? and what is getApplicableConstructorTypes, what is visitMethodCall?
Is there any document about this? or i just have to see the source code?
i am a beginner, hopes that anyone can teach me ,thanks!

**Comment by creativityingenuity** [comment]
me too
